version: "3.9"

services:
  bootstrap:
    image: alpine:3.20
    container_name: portable-bootstrap
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./library:/project
    command: >-
      sh -c '
        set -e;
        echo "[bootstrap] Ensuring directory tree";
        for d in \
          configs/audiobookshelf \
          configs/qbittorrent \
          data/mariadb \
          data/booklore \
          data/audiobookshelf \
          media/books \
          media/audiobooks \
          media/podcasts \
          ingest/booklore \
          downloads/complete \
          downloads/incomplete \
          downloads/watch; do
            mkdir -p /project/"$d"; 
          done;
        echo "[bootstrap] Adjusting ownership (may fail harmlessly on some systems)";
        chown -R ${PUID}:${PGID} /project/configs /project/data /project/media /project/downloads /project/ingest 2>/dev/null || true;
        echo ready > /tmp/ready;
        # keep container around so healthcheck remains healthy
        tail -f /dev/null;
      '
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: "no"

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: mariadb
    depends_on:
      bootstrap:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booklore
      - MYSQL_USER=booklore
      - MYSQL_PASSWORD=bjbjbjbj
    volumes:
      - ./library/data/mariadb:/config
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  booklore:
    image: booklore/booklore:latest
    container_name: booklore
    depends_on:
      bootstrap:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/booklore
      - DATABASE_USERNAME=booklore
      - DATABASE_PASSWORD=bjbjbjbj
      - SWAGGER_ENABLED=false
    ports:
      - "6060:6060"
    volumes:
      - ./library/data/booklore:/app/data
      - ./library/media/books:/books
      - ./library/ingest/booklore:/bookdrop
    restart: unless-stopped

  book-downloader-booklore:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: booklore-book-downloader
    depends_on:
      bootstrap:
        condition: service_healthy
      booklore:
        condition: service_started
    environment:
      - TZ=${TZ}
      - UID=${PUID}
      - GID=${PGID}
      - USE_BOOK_TITLE=true
    ports:
      - "8084:8084"
    volumes:
      - ./library/ingest/booklore:/cwa-book-ingest
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    depends_on:
      bootstrap:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "13378:80"
    volumes:
      - ./library/configs/audiobookshelf:/config
      - ./library/data/audiobookshelf:/metadata
      - ./library/media/audiobooks:/audiobooks
      - ./library/media/podcasts:/podcasts
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      bootstrap:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./library/configs/qbittorrent:/config
      - ./library/downloads:/downloads
    restart: unless-stopped

networks:
  default:
    name: portable-library
